version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build_and_test:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.version >>-buster-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Which ruby?
          command: ruby -v
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Test
          command: rake test
workflows:
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              version: ["2.6.3", "2.6.5", "2.6", "2.7", "3"]