version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Test
          command: rake test
workflows:
  build_and_test:
    jobs:
      - build_and_test